name: werf
author: 'Flant'
description: 'Use werf CI/CD tool and GitHub Actions to build Docker images, push them to the registry, deploy to Kubernetes, and more!'
branding:
  color: blue
  icon: anchor
inputs:
  channel:
    description: 'The one of the following channel: alpha, beta, ea, stable, rock-solid'
    default: 'alpha'
    required: false
  version:
    description: 'The certain version'
    required: false
  env:
    description: 'Specific deployment environment'
    required: true
  github-token:
    description: 'The GitHub token used to login and to interact with Docker Github Packages'
    default: ${{ github.token }}
    required: false
  kube-config-base64-data:
    description: 'Base64 encoded kubeconfig data used for deployment, cleanup and distributed locks'
    required: false
runs:
  using: 'node12'
  main: 'converge/index.js'
