name: werf run
author: 'Flant'
description: 'Prepare the environment and run built image with werf'
branding:
  color: blue
  icon: anchor
inputs:
  channel:
    description: 'The one of the following channel: alpha, beta, ea, stable, rock-solid'
    default: 'alpha'
    required: false
  version:
    description: 'The certain version'
    required: false
  image:
    description: 'The image name from werf.yaml (werf run [options] [IMAGE_NAME] [-- COMMAND ARG...])'
    required: false
  args:
    description: 'The specific command with arguments (werf run [options] [IMAGE_NAME] [-- COMMAND ARG...])'
    required: false
  github-token:
    description: 'The GitHub token used to login and to interact with Docker Github Packages'
    default: ${{ github.token }}
    required: false
  kube-config-base64-data:
    description: 'Base64 encoded kubeconfig data used for deployment, cleanup and distributed locks'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
